version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com

  build:
    commands:
      - echo Building Backend Docker image...
      - docker build -t g1-repo1-backend -f Backend/Dockerfile Backend
      - docker tag g1-repo1-backend:latest 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g1-repo1:backend

  post_build:
    commands:
      - echo Pushing Backend Docker image to ECR...
      - docker push 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g1-repo1:backend
      - echo Writing image definitions...
      - printf '[{"name":"BackEnd","imageUri":"124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g1-repo1:backend"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
